language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

env:
  global:
    - PYTHONWARNINGS="default,ignore::PendingDeprecationWarning,ignore::ResourceWarning"
  matrix:
    - DB="POSTGRESQL"
    - DB="MYSQL"

sudo: false

cache: pip

addons:
  postgresql: "9.3"
  mysql: "5.5"
  apt:
    packages:
      - rsyslog

before_install:
  - pip install codecov
  - pip install -e git+https://github.com/modoboa/modoboa.git#egg=modoboa

install:
  - pip install -r requirements.txt
  - pip install -r test-requirements.txt
  - python setup.py develop

script:
  - cd test_project
  - coverage run --source ../modoboa_postfix_autoreply manage.py test --nomigrations modoboa_postfix_autoreply.tests

after_success:
  - codecov

before_deploy:
  - cd ../modoboa_postfix_autoreply
  - django-admin compilemessages
  - cd ..

deploy:
  provider: pypi
  user: tonio
  password:
    secure: KGr/3pz3ynbIBVYAHwUhibqRqCWCE6itWqDgKizkERUhhxdyXzjxo662EW1V4Ahu6rg8pHcDT33IAIc9zKqGFzpJa1d7rlY2lcJll3wXzIcqDonB8Wo8YfwytP4WbxNYYEfcKI5W4eB7MiuccGz5TYO837df+QQNDMrhq0ScLws=
  skip_cleanup: true
  distributions: "sdist bdist_wheel"
  on:
    tags: true
    python: "3.6"
    condition: $DB = POSTGRESQL
